CORE-702: Validation call from CLI PR
DataDog/chaos-controller pull request #320
Opened 2021-05-27 11:34 UTC by nathan-tournant

## What does this PR do?

- [X] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves Documentation

A brief description of changes to implementation or controller behavior:
Whole validation is now called from the CLI command `chaosli validate --...`

Motivation for change:

## Code Quality

### Testing

- [ ] I used existing unit tests
- [X] I manually tested locally
- [ ] I will manually test in a canary deployment

Please list your manual testing steps (sample `yaml` file, commands, important checks):

### Checklist

- [X] The documentation is up to date
- [X] My code is sufficiently commented
- [X] I have tested to the best of my ability
- [X] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md))

2021-05-27 12:42 UTC, ptnapoleon requested changes

2021-05-27 13:03 UTC, nathan-tournant commented on api/v1beta1/disruption_spec.go
> +	chaosapi "github.com/DataDog/chaos-controller/api"
I'll trust you on this and revert the file name

2021-05-28 16:55 UTC, ptnapoleon commented on cli/chaosli/cmd/validate.go
> +		return fmt.Errorf("no path given, exiting")
Can you go ahead and remove `pathError` from `root.go` and make explain also call this function in its `PreRunE`?

2021-06-01 10:32 UTC, Devatoria approved these changes

2021-06-01 13:15 UTC, ptnapoleon approved these changes

2021-06-01 13:23 UTC, merged