CHAOS-785: Add new config for node level allowed hosts
DataDog/chaos-controller pull request #783
Opened 2023-09-27 16:15 UTC by ptnapoleon

## What does this PR do?

- [ ] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- Technically we considered changing the current allowedHosts field to only apply during node level disruptions, but this is fairly breaking change so I wasn't sure
- The naming of the new field is horrible, please advise
- Essentially, some users want to disrupt connection to the core components that we currently have on our allowlist. As long as they're doing this with pod level disruptions against their own apps, that should be totally fine. So we should restrict the allowlist to only node level disruptions

## Code Quality Checklist

- [ ] The documentation is up to date.
- [ ] My code is sufficiently commented and passes continuous integration checks.
- [ ] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [ ] I leveraged continuous integration testing
    - [ ] by depending on existing `unit` tests or `end-to-end` tests.
    - [ ] by adding new `unit` tests or `end-to-end` tests.
- [ ] I manually tested the following steps:
    - `x`
    - [ ] locally.
    - [ ] as a canary deployment to a cluster.

2023-09-28 07:45 UTC, luphaz submitted a review, later dismissed
It seems fair to introduce a new configuration instead of breaking the previous behaviour.

The new name is clear for me at least 😉

2023-09-28 07:45 UTC, luphaz commented on chart/templates/configmap.yaml
> +          {{- range $index, $allowedHost := .Values.injector.networkDisruption.allowedHosts }}
```suggestion
          {{- range $index, $allowedHost := .Values.injector.networkDisruption.nodeLevelAllowedHosts }}
```

2023-10-03 08:37 UTC, aymericDD approved these changes

2023-10-03 08:46 UTC, Devatoria commented
I'm a bit confused about having one field for node level only and one field for both node and pod levels, they are overlapping. What do you think about having both `podLevelAllowedHosts` and `nodeLevelAllowedHosts` (or `allowedHostsPod/NodeLevel` if we prefer to suffix instead) as new fields? We can keep the general `allowedHosts` for now in the CRD and use the admission webhook to fill both new fields (`pod/nodeLevelAllowedHosts`) with `allowedHosts` values when specified for retro compatibility. We would deprecate that field until future release.

It means we would have a configuration like:
```
networkDisruptions:
    podLevelAllowedHosts: [] // pod level only
    nodeLevelAllowedHosts: [] // node level only
    allowedHosts: [] // DEPRECATED: both pod and node level
```

2023-10-03 08:47 UTC, Devatoria requested changes
Blocking until we discussed the comment I left on the PR to avoid too fast merge

2023-10-03 16:09 UTC, ptnapoleon commented
Hmm. Well, we don't have any use cases for podLevelAllowedHosts, and we don't even have any use cases for allowedHosts anymore... Do we just want to deprecate the old field and _only_ have nodeLevelAllowedHosts?

2023-10-13 17:28 UTC, ptnapoleon commented
Rather than break our config and make it more complicated to use, we should just inform users to use `disableDefaultAllowedHosts` in their spec when necessary

2023-10-13 17:28 UTC, closed without merging